import { build } from "esbuild";
import { writeFileSync } from "fs";
import path from "path";

await build({
  entryPoints: ["src/cf-worker-entry.ts"],
  bundle: true,
  platform: "neutral",
  target: "esnext",
  format: "esm",
  outfile: "dist/_worker.js",
  alias: { "@": path.resolve("src") },
  // CF Workers built-in modules
  external: ["cloudflare:sockets", "node:*"],
  conditions: ["workerd", "worker", "browser"],
  mainFields: ["module", "main"],
  banner: { js: "// Auto-generated by scripts/build-worker.mjs — do not edit" },
  define: {
    "process.env.NODE_ENV": '"production"',
    // public-config.ts の import.meta.env.PROD 分岐を prod 側に解決させる。
    // client は Vite が、dev worker は Vite dev server が同じ変数を提供する。
    "import.meta.env.PROD": "true",
    "import.meta.env.DEV": "false",
    "import.meta.env.MODE": '"production"',
  },
});

// Prevent _worker.js from being uploaded as a static asset
writeFileSync("dist/.assetsignore", "_worker.js\n");

console.log("✓ Worker bundled → dist/_worker.js");
console.log("✓ dist/.assetsignore generated");
